<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Contacts' => 'Контакты',
    'Fax' => 'Факс',
    'GSP-105, Nizhny Novgorod, 603950, Russia' => 'ГСП-105, Нижний Новгород, 603950, Россия',
    'IPM RAS' => 'ИФМ РАН',
    'International Symposium' => 'Международный симпозиум',
    'March, 10-13, 2020' => '10-13 марта 2020',
    'Maria Vladimirovna Zorina' => 'Мария Владимировна Зорина',
    'My office' => 'Личный кабинет',
    'Nizhny Novgorod' => 'Нижний Новгород',
    'Ph.' => 'Тел.',
    'Phone' => 'Телефон',
    'Sponsors' => 'Спонсоры',
    'Venue' => 'Место проведения',
    'Vladimir Vladimirovich Rumyantsev' => 'Владимир Владимирович Румянцев',
    'scientific secretary of the Symposium' => 'ученый секретарь симпозиума',
    '“Nanophysics & Nanoelectronics”' => '«Нанофизика и наноэлектроника»',
    'Important dates' => 'Важные даты',
    'Nizhny&nbsp;Novgorod' => '@@Нижний Новгород@@',
];
